In [1]:
import pandas as pd

In [2]:
env_expend_rev_file = "../Data/original_env_expend_rev.csv"

In [3]:
env_expend_rev_csv = pd.read_csv(env_expend_rev_file)
env_expend_rev_df = pd.DataFrame(env_expend_rev_csv)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
env_expend_rev_df = env_expend_rev_df.loc[env_expend_rev_df['Measure'] == 'Millions USD, 2010 PPP prices'].reset_index()

In [12]:
env_expend_rev_df = env_expend_rev_df.rename(columns={'Value' : 'Millions USD, 2010 PPP prices', 'COU' : 'Country Code'})

In [13]:
env_expend_rev_df.columns.values

array(['index', 'Country Code', 'Country', 'TABLES', 'Tables', 'SEC',
       'Sector', 'IND', 'Industry', 'EXP', 'Expenditure', 'MEASURE',
       'Measure', 'YEA', 'Year', 'Millions USD, 2010 PPP prices',
       'Flag Codes', 'Flags'], dtype=object)

In [14]:
env_expend_rev_df = env_expend_rev_df[['Country Code', 'Country', 'Tables', 'Sector', 'Industry', 'Expenditure', 'Year', 'Millions USD, 2010 PPP prices', 'Flag Codes', 'Flags']]

In [19]:
env_expend_rev_df['Flags'] = env_expend_rev_df['Flags'].fillna('Actual value')
env_expend_rev_df['Flag Codes'] = env_expend_rev_df['Flag Codes'].fillna('A')

env_expend_rev_df['Flags'].value_counts()

Actual value                              172951
Non-publishable and confidential value      1512
Estimated value                              443
Break                                        189
Name: Flags, dtype: int64

In [23]:
env_expend_rev_df.loc[(env_expend_rev_df['Flags'] == 'Break') | (env_expend_rev_df['Flags'] == 'Estimated value')\
                      | (env_expend_rev_df['Flags'] == 'Non-publishable and confidential value'), :]

,Country Code,Country,Tables,Sector,Industry,Expenditure,Year,"Millions USD, 2010 PPP prices",Flag Codes,Flags
223,AUT,Austria,Public sector,Air,NaN,Investments,1997,4.698623,B,Break
698,AUT,Austria,Public sector,Total,NaN,Investments,1997,45.813030,B,Break
814,AUT,Austria,Public sector,Waste,NaN,Investments,1997,0.230607,B,Break
930,AUT,Austria,Public sector,Wastewater,NaN,Investments,1997,9.901699,B,Break
2643,AUT,Austria,Public sector,Air,NaN,Total current expenditure,1997,28.047610,B,Break
3118,AUT,Austria,Public sector,Total,NaN,Total current expenditure,1997,472.658400,B,Break
3234,AUT,Austria,Public sector,Waste,NaN,Total current expenditure,1997,10.031420,B,Break
3350,AUT,Austria,Public sector,Wastewater,NaN,Total current expenditure,1997,57.839180,B,Break
7505,AUT,Austria,Public sector,Air,NaN,Subsidies and transfers,1997,197.486300,B,Break
8010,AUT,Austria,Public sector,Total,NaN,Subsidies and transfers,1997,944.891500,B,Break
8129,AUT,Austria,Public sector,Waste,NaN,Subsidies and transfers,1997,157.720900,B,Break
8248,AUT,Austria,Public sector,Wastewater,NaN,Subsidies and transfers,1997,336.138900,B,Break
11221,BEL,Belgium,Business sector total,Air,NaN,Investments in integrated technologies,2008,NaN,C,Non-publishable and confidential value
11222,BEL,Belgium,Business sector total,Air,NaN,Investments in integrated technologies,2009,NaN,C,Non-publishable and confidential value
11223,BEL,Belgium,Business sector total,Air,NaN,Investments in integrated technologies,2010,NaN,C,Non-publishable and confidential value
11225,BEL,Belgium,Business sector total,Air,NaN,Investments in integrated technologies,2012,NaN,C,Non-publishable and confidential value
11226,BEL,Belgium,"Electricity, gas, steam, air conditioning, water",Air,NaN,Investments in integrated technologies,2007,NaN,C,Non-publishable and confidential value
11227,BEL,Belgium,"Electricity, gas, steam, air conditioning, water",Air,NaN,Investments in integrated technologies,2008,NaN,C,Non-publishable and confidential value
11240,BEL,Belgium,Mining and quarrying,Air,NaN,Investments in integrated technologies,2009,NaN,C,Non-publishable and confidential value
11241,BEL,Belgium,Mining and quarrying,Air,NaN,Investments in integrated technologies,2010,NaN,C,Non-publishable and confidential value
11243,BEL,Belgium,Mining and quarrying,Air,NaN,Investments in integrated technologies,2012,NaN,C,Non-publishable and confidential value
11344,BEL,Belgium,Business sector total,Waste,NaN,Investments in integrated technologies,2008,NaN,C,Non-publishable and confidential value
11345,BEL,Belgium,Business sector total,Waste,NaN,Investments in integrated technologies,2009,NaN,C,Non-publishable and confidential value
11346,BEL,Belgium,Business sector total,Waste,NaN,Investments in integrated technologies,2010,NaN,C,Non-publishable and confidential value
11348,BEL,Belgium,Business sector total,Waste,NaN,Investments in integrated technologies,2012,NaN,C,Non-publishable and confidential value
11349,BEL,Belgium,"Electricity, gas, steam, air conditioning, water",Waste,NaN,Investments in integrated technologies,2007,NaN,C,Non-publishable and confidential value
11350,BEL,Belgium,"Electricity, gas, steam, air conditioning, water",Waste,NaN,Investments in integrated technologies,2008,NaN,C,Non-publishable and confidential value
11363,BEL,Belgium,Mining and quarrying,Waste,NaN,Investments in integrated technologies,2009,NaN,C,Non-publishable and confidential value
11364,BEL,Belgium,Mining and quarrying,Waste,NaN,Investments in integrated technologies,2010,NaN,C,Non-publishable and confidential value
11366,BEL,Belgium,Mining and quarrying,Waste,NaN,Investments in integrated technologies,2012,NaN,C,Non-publishable and confidential value
...,...,...,...,...,...,...,...,...,...,...
142168,TUR,Turkey,"Electricity, gas, steam, air conditioning, water",Other,NaN,Receipts from by-products,2010,NaN,C,Non-publishable and confidential value
142176,TUR,Turkey,Mining and quarrying,Other,NaN,Receipts from by-products,2009,NaN,C,Non-publishable and confidential value
142179,TUR,Turkey,Other business,Other,NaN,Receipts from by-products,2010,NaN,C,Non-publishable and confidential value
142304,TUR,Turkey,"Electricity, gas, steam, air conditioning, water",Wastewater,NaN,Receipts from by-products,2010,NaN,C,Non-publishable and confidential value
142307,TUR,Turkey,Total manufacturing,Wastewater,NaN,Receipts from by-products,2009,NaN,C,Non-publishable and confidential value
142308,TUR,Turkey,Total manufacturing,Wastewater,NaN,Receipts from by-products,2010,NaN,C,Non-publishable and confidential value
142312,TUR,Turkey,Mining and quarrying,Wastewater,NaN,Receipts from by-products,2009,NaN,C,Non-publishable and confidential value
142315,TUR,Turkey,Other business,Wastewater,NaN,Receipts from by-products,2009,NaN,C,Non-publishable and confidential value
143888,GBR,United Kingdom,"Electricity, gas, steam, air conditioning, water",Noise,NaN,Investments,2005,0.000000,E,Estimated value
143889,GBR,United Kingdom,"Electricity, gas, steam, air conditioning, water",Noise,NaN,Investments,2006,0.000000,E,Estimated value
145861,GBR,United Kingdom,Mining and quarrying,Biodiversity and Landscape,NaN,End-of-pipe investments,2005,0.000000,E,Estimated value
146075,GBR,United Kingdom,Mining and quarrying,Soil and groundwater,NaN,End-of-pipe investments,2006,0.000000,E,Estimated value
147851,GBR,United Kingdom,"Electricity, gas, steam, air conditioning, water",Biodiversity and Landscape,NaN,Fees and purchases,2001,0.000000,E,Estimated value
147863,GBR,United Kingdom,Total manufacturing,Biodiversity and Landscape,NaN,Fees and purchases,2001,0.000000,E,Estimated value
147900,GBR,United Kingdom,"Electricity, gas, steam, air conditioning, water",Noise,NaN,Fees and purchases,2001,0.000000,E,Estimated value
147912,GBR,United Kingdom,Total manufacturing,Noise,NaN,Fees and purchases,2001,0.000000,E,Estimated value
164697,SVN,Slovenia,Mining and quarrying,Air,NaN,Investments,2002,0.000000,E,Estimated value
164698,SVN,Slovenia,Mining and quarrying,Air,NaN,Investments,2003,0.000000,E,Estimated value
164773,SVN,Slovenia,Total manufacturing,Biodiversity and Landscape,NaN,Investments,2006,0.000000,E,Estimated value
164866,SVN,Slovenia,Mining and quarrying,Noise,NaN,Investments,2003,0.000000,E,Estimated value
164867,SVN,Slovenia,Mining and quarrying,Noise,NaN,Investments,2004,0.000000,E,Estimated value
164868,SVN,Slovenia,Mining and quarrying,Noise,NaN,Investments,2005,0.000000,E,Estimated value
164869,SVN,Slovenia,Mining and quarrying,Noise,NaN,Investments,2006,0.000000,E,Estimated value
165319,SVN,Slovenia,Mining and quarrying,Waste,NaN,Investments,2002,0.000000,E,Estimated value
165320,SVN,Slovenia,Mining and quarrying,Waste,NaN,Investments,2003,0.000000,E,Estimated value
165322,SVN,Slovenia,Mining and quarrying,Waste,NaN,Investments,2005,0.000000,E,Estimated value
165416,SVN,Slovenia,Mining and quarrying,Wastewater,NaN,Investments,2003,0.000000,E,Estimated value
165417,SVN,Slovenia,Mining and quarrying,Wastewater,NaN,Investments,2004,0.000000,E,Estimated value
165418,SVN,Slovenia,Mining and quarrying,Wastewater,NaN,Investments,2005,0.000000,E,Estimated value
167292,SVN,Slovenia,Total manufacturing,Biodiversity and Landscape,NaN,End-of-pipe investments,2006,0.000000,E,Estimated value