In [1]:
import pandas as pd

In [2]:
emission = pd.read_csv('../Data/AIR_pollution.csv')

In [3]:
emission.head()

,COU,Country,POL,Pollutant,VAR,Variable,YEA,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1990,1990,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,419843.155,NaN,NaN
1,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1991,1991,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,420927.191,NaN,NaN
2,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1992,1992,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,425820.883,NaN,NaN
3,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1993,1993,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,426128.333,NaN,NaN
4,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1994,1994,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,426074.577,NaN,NaN

In [4]:
del emission['COU']
del emission['POL']
del emission['Pollutant']
del emission['VAR']
del emission['YEA']
del emission['Unit Code']
del emission['PowerCode Code']
del emission['Reference Period Code']
del emission['Reference Period']
del emission['Flag Codes']
del emission['Flags']
del emission['PowerCode']

In [5]:
emission['Variable'].value_counts()

Total  emissions excluding LULUCF                   7216
Total GHG, Index 2000=100                           7079
Total GHG per unit of GDP                           1048
Total GHG per capita                                1048
Total GHG, Index 1990=100                           1027
3 - Agriculture                                     1021
1 - Energy                                          1021
2- Industrial processes and product use             1021
5 - Waste                                           1021
Land use, land-use change and forestry (LULUCF)     1013
Total  emissions including LULUCF                    982
1A3 - Transport                                      977
1A1 - Energy Industries                              975
1A2 - Manufacturing industries and construction      975
1A4 - Other sectors                                  960
1B - Fugitive Emissions from Fuels                   896
1A5 - Energy - Other                                 691
6 - Other                                             90
1C - CO2 from Transport and Storage                   62
Name: Variable, dtype: int64

In [6]:
#the total emission is the only one we want?

for i, g in emission.groupby('Variable'):
    if i == "Total  emissions excluding LULUCF":   
        g.to_csv('../Data/clean_TotalGazEmission.csv'.format(i), header=True, index_label=True)