In [1]:
import pandas as pd
file = "GHG.csv"
df_original = pd.read_csv(file)

In [2]:
df_original.head()

,COU,Country,POL,Pollutant,VAR,Variable,YEA,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1990,1990,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,419843.155,NaN,NaN
1,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1991,1991,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,420927.191,NaN,NaN
2,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1992,1992,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,425820.883,NaN,NaN
3,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1993,1993,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,426128.333,NaN,NaN
4,AUS,Australia,GHG,Greenhouse gases,TOTAL,Total emissions excluding LULUCF,1994,1994,T_CO2_EQVT,Tonnes of CO2 equivalent,3,Thousands,NaN,NaN,426074.577,NaN,NaN

In [3]:
pollutes = df_original[["Country","POL","Variable","Year","Unit","Value"]]

In [13]:
#Pollutes = GHG
GHG = pollutes.loc[pollutes["POL"] == "GHG",:]
GHG = GHG.reset_index(drop=True)

#print(len(GHG))

GHG_including_LULUCF = GHG.loc[GHG["Variable"] == "Total  emissions including LULUCF",:]
GHG_including_LULUCF = GHG_including_LULUCF.reset_index(drop=True)

GHG_excluding_LULUCF = GHG.loc[GHG["Variable"] == "Total  emissions excluding LULUCF",:]
GHG_excluding_LULUCF = GHG_excluding_LULUCF.reset_index(drop=True)

GHG_2000 = GHG.loc[GHG["Variable"] == "Total GHG, Index 2000=100",:]
GHG_2000 = GHG_2000.reset_index(drop=True)

GHG_total_capita = GHG.loc[GHG["Variable"] == "Total GHG per capita",:]
GHG_total_capita = GHG_total_capita.reset_index(drop=True)

GHG_Energy = GHG.loc[GHG["Variable"]=="1 - Energy",:]
GHG_Energy = GHG_Energy.reset_index(drop=True)

GHG_Energy_MC = GHG.loc[GHG["Variable"]=="1A2 - Manufacturing industries and construction",:]
GHG_Energy_MC = GHG_Energy_MC.reset_index(drop=True)

GHG_Energy_Trans = GHG.loc[GHG["Variable"]=="1A3 - Transport",:]
GHG_Energy_Trans = GHG_Energy_Trans.reset_index(drop=True)

GHG_industrial = GHG.loc[GHG["Variable"]=="2- Industrial processes and product use",:]
GHG_industrial = GHG_industrial.reset_index(drop=True)

GHG_Agriculture = GHG.loc[GHG["Variable"]=="3 - Agriculture",:]
GHG_Agriculture = GHG_Agriculture.reset_index(drop=True)

GHG_Waste = GHG.loc[GHG["Variable"]=="5 - Waste",:]
GHG_Waste = GHG_Waste.reset_index(drop=True)

GHG_Other = GHG.loc[GHG["Variable"]=="6 - Other",:]
GHG_Other = GHG_Other.reset_index(drop=True)

#Export to CSV
GHG_including_LULUCF.to_csv('GHG_CLEAN_DATA/clean_GHG_including_LULUCF.csv', header=True, index_label=True)
GHG_excluding_LULUCF.to_csv('GHG_CLEAN_DATA/clean_GHG_excluding_LULUCF.csv', header=True, index_label=True)
GHG_2000.to_csv('GHG_CLEAN_DATA/clean_GHG_index_2000.csv', header=True, index_label=True)
GHG_Energy.to_csv('GHG_CLEAN_DATA/clean_GHG_Energy.csv', header=True, index_label=True)
GHG_Energy_Trans.to_csv('GHG_CLEAN_DATA/clean_GHG_Transport.csv', header=True, index_label=True)
GHG_industrial.to_csv('GHG_CLEAN_DATA/clean_GHG_industrial.csv', header=True, index_label=True)
GHG_Agriculture.to_csv('GHG_CLEAN_DATA/clean_GHG_Agriculture.csv', header=True, index_label=True)
GHG_Waste.to_csv('GHG_CLEAN_DATA/clean_GHG_Waste.csv', header=True, index_label=True)
GHG_Other.to_csv('GHG_CLEAN_DATA/clean_GHG_OtherEnergy.csv', header=True, index_label=True)
GHG_Energy_MC.to_csv('GHG_CLEAN_DATA/clean_GHG_Manufacturing_Construction.csv', header=True, index_label=True)
GHG.to_csv('GHG_CLEAN_DATA/clean_GHG.csv', header=True, index_label=True)
GHG_total_capita.to_csv('GHG_CLEAN_DATA/clean_GHG_per_capita.csv', header=True, index_label=True)

16917

In [5]:
#Pollutes = CO2
CO2 = pollutes.loc[pollutes["POL"] == "CO2",:]
CO2 = CO2.reset_index(drop=True)

CO2_excluding_LULUCF = CO2.loc[CO2["Variable"] == "Total  emissions excluding LULUCF",:]
CO2_excluding_LULUCF = CO2_excluding_LULUCF.reset_index(drop=True)

CO2_2000 = CO2.loc[CO2["Variable"] == "Total GHG, Index 2000=100",:]
CO2_2000 = CO2_2000.reset_index(drop=True)

#Export to CSV
CO2.to_csv('CO2_CLEAN_DATA/clean_CO2.csv', header=True, index_label=True)
CO2_excluding_LULUCF.to_csv('CO2_CLEAN_DATA/clean_CO2_exclude_LULUCF.csv', header=True, index_label=True)
CO2_2000.to_csv('CO2_CLEAN_DATA/clean_CO2_index_2000.csv', header=True, index_label=True)

In [7]:
#Pollutes = Methane
CH4 = pollutes.loc[pollutes["POL"] == "CH4",:]
CH4 = CH4.reset_index(drop=True)

CH4_excluding_LULUCF = CH4.loc[CH4["Variable"] == "Total  emissions excluding LULUCF",:]
CH4_excluding_LULUCF = CH4_excluding_LULUCF.reset_index(drop=True)

CH4_2000 = CH4.loc[CH4["Variable"] == "Total GHG, Index 2000=100",:]
CH4_2000 = CH4_2000.reset_index(drop=True)

#Export to CSV
CH4.to_csv('CH4_CLEAN_DATA/clean_CH4.csv', header=True, index_label=True)
CH4_excluding_LULUCF.to_csv('CH4_CLEAN_DATA/clean_CH4_exclude_LULUCF.csv', header=True, index_label=True)
CH4_2000.to_csv('CH4_CLEAN_DATA/clean_CH4_index_2000.csv', header=True, index_label=True)

In [29]:
pollutes_mer = pollutes.groupby("Country")
pollutes_mer.head()

,Country,POL,Variable,Year,Unit,Value
0,Australia,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,419843.155
1,Australia,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,420927.191
2,Australia,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,425820.883
3,Australia,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,426128.333
4,Australia,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,426074.577
234,Austria,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,78804.650
235,Austria,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,82630.838
236,Austria,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,75924.575
237,Austria,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,75967.667
238,Austria,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,76501.242
468,Belgium,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,146294.177
469,Belgium,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,145485.629
470,Belgium,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,145363.118
471,Belgium,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,144343.376
472,Belgium,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,152160.400
700,Canada,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,611000.782
701,Canada,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,603824.477
702,Canada,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,621187.417
703,Canada,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,622898.400
704,Canada,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,644272.876
932,Czech Republic,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,195827.078
933,Czech Republic,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,177149.062
934,Czech Republic,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,170408.665
935,Czech Republic,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,162605.625
936,Czech Republic,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,154904.697
1156,Denmark,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,70574.077
1157,Denmark,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,81220.195
1158,Denmark,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,75218.969
1159,Denmark,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,77411.841
1160,Denmark,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,81307.537
...,...,...,...,...,...,...
19712,China (People's Republic of),GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,4057617.000
19713,China (People's Republic of),GHG,Total emissions excluding LULUCF,2005,Tonnes of CO2 equivalent,7465861.700
19714,China (People's Republic of),GHG,1 - Energy,1994,Tonnes of CO2 equivalent,3007780.000
19715,China (People's Republic of),GHG,1 - Energy,2005,Tonnes of CO2 equivalent,5769854.800
19716,China (People's Republic of),GHG,2- Industrial processes and product use,1994,Tonnes of CO2 equivalent,282631.000
19745,Colombia,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,56305.297
19746,Colombia,GHG,Total emissions excluding LULUCF,1995,Tonnes of CO2 equivalent,67946.476
19747,Colombia,GHG,Total emissions excluding LULUCF,2000,Tonnes of CO2 equivalent,70989.605
19748,Colombia,GHG,Total emissions excluding LULUCF,2001,Tonnes of CO2 equivalent,69532.053
19749,Colombia,GHG,Total emissions excluding LULUCF,2002,Tonnes of CO2 equivalent,69318.093
20030,Costa Rica,GHG,Total emissions excluding LULUCF,2005,Tonnes of CO2 equivalent,10878.070
20031,Costa Rica,GHG,Total emissions excluding LULUCF,2010,Tonnes of CO2 equivalent,12511.350
20032,Costa Rica,GHG,Total emissions excluding LULUCF,2012,Tonnes of CO2 equivalent,13257.360
20033,Costa Rica,GHG,1 - Energy,2005,Tonnes of CO2 equivalent,5922.140
20034,Costa Rica,GHG,1 - Energy,2010,Tonnes of CO2 equivalent,7027.660
20069,India,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,1214248.000
20070,India,GHG,Total emissions excluding LULUCF,2000,Tonnes of CO2 equivalent,1523766.600
20071,India,GHG,1 - Energy,1994,Tonnes of CO2 equivalent,743820.000
20072,India,GHG,1 - Energy,2000,Tonnes of CO2 equivalent,1027016.500
20073,India,GHG,2- Industrial processes and product use,1994,Tonnes of CO2 equivalent,102710.000
20102,Indonesia,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,266818.400
20103,Indonesia,GHG,Total emissions excluding LULUCF,1991,Tonnes of CO2 equivalent,292610.400
20104,Indonesia,GHG,Total emissions excluding LULUCF,1992,Tonnes of CO2 equivalent,306828.600
20105,Indonesia,GHG,Total emissions excluding LULUCF,1993,Tonnes of CO2 equivalent,318657.500
20106,Indonesia,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,334191.200
20303,South Africa,GHG,Total emissions excluding LULUCF,1990,Tonnes of CO2 equivalent,347349.400
20304,South Africa,GHG,Total emissions excluding LULUCF,1994,Tonnes of CO2 equivalent,379837.200
20305,South Africa,GHG,1 - Energy,1990,Tonnes of CO2 equivalent,260889.500
20306,South Africa,GHG,1 - Energy,1994,Tonnes of CO2 equivalent,297566.400
20307,South Africa,GHG,2- Industrial processes and product use,1990,Tonnes of CO2 equivalent,30791.800